### ISSUE TITLE
SOURCE stages get scheduled on coordinator

### ISSUE THREAD

**Issue by sopel39** [prestosql/presto#2811]
Source stage get scheduler on coordinator even though `node-scheduler.include-coordinator=false`

![Zrzut ekranu 2020-02-12 o 23 12 56](https://user-images.githubusercontent.com/5989165/74382368-97f19000-4ded-11ea-9892-7a60472ecd74.png)
![Zrzut ekranu 2020-02-12 o 23 13 22](https://user-images.githubusercontent.com/5989165/74382370-9922bd00-4ded-11ea-9003-5a846b2d4440.png)
![Zrzut ekranu 2020-02-12 o 23 13 32](https://user-images.githubusercontent.com/5989165/74382372-99bb5380-4ded-11ea-8674-b81ecd8df8f2.png)
![Zrzut ekranu 2020-02-12 o 23 14 12](https://user-images.githubusercontent.com/5989165/74382376-9aec8080-4ded-11ea-9640-9a073c029112.png)

**Comment by sopel39** [comment]
Hash stages are queued on workers only:
![Zrzut ekranu 2020-02-12 o 23 20 55](https://user-images.githubusercontent.com/5989165/74382831-60371800-4dee-11ea-9a97-4448cac1d6a8.png)
![Zrzut ekranu 2020-02-12 o 23 21 01](https://user-images.githubusercontent.com/5989165/74382837-61684500-4dee-11ea-9b60-084b4ed8b8c8.png)

**Comment by sopel39** [comment]
FYI: @dain @electrum

**Comment by sopel39** [comment]
I think this is fixed by: https://github.com/prestosql/presto/pull/2714

**Comment by stagraqubole** [comment]
@sopel39 Was this with hdfs table? #2714 will hit only when split has address in it.

**Comment by sopel39** [comment]
This was S3 table. I think it sets location in  `io.prestosql.plugin.hive.s3.PrestoS3FileSystem#createLocatedFileStatus` 
to `localhost`, which I think is filtered out in `io.prestosql.plugin.hive.util.InternalHiveSplitFactory#getHostAddresses`.

Therefore this might be a different bug

**Comment by sopel39** [comment]
@stagraqubole would you like to investigate it?

**Comment by stagraqubole** [comment]
What's the query you used @sopel39 ? I tried with a simple join on bigger scale `select count(*) from store_sales join customer on ss_customer_sk = c_customer_sk` and did not see this issue.

**Comment by sopel39** [comment]
I think that was tpcds/q64 with unpartitioned S3 data.

**Comment by stagraqubole** [comment]
No luck with query64 too, no work on master with table on S3 with or without the fix #2714 

@sopel39 from the task list shared, all but master node got ~400 splits and master go only 64. This kind of distribution does point to the bug fixed in #2714 where only during redistribution master node can be picked. The only thing unexplainable is how it is hit for S3. Are you using any caching in between like Alluxio? It might be adding addresses to splits.

**Comment by sopel39** [comment]
@stagraqubole Sorry, the query is `q23_1`, specifically: 
```
WITH
frequent_ss_items AS (
SELECT
"substr"("i_item_desc", 1, 30) "itemdesc"
, "i_item_sk" "item_sk"
, "d_date" "solddate"
, "count"(*) "cnt"
FROM
hive.tpcds_sf300_orc.store_sales
, hive.tpcds_sf300_orc.date_dim
, hive.tpcds_sf300_orc.item
WHERE ("ss_sold_date_sk" = "d_date_sk")
AND ("ss_item_sk" = "i_item_sk")
AND ("d_year" IN (2000   , (2000 + 1)   , (2000 + 2)   , (2000 + 3)))
GROUP BY "substr"("i_item_desc", 1, 30), "i_item_sk", "d_date"
HAVING ("count"(*) > 4)
)
, max_store_sales AS (
SELECT "max"("csales") "tpcds_cmax"
FROM
(
SELECT
"c_customer_sk"
, "sum"(("ss_quantity" * "ss_sales_price")) "csales"
FROM
hive.tpcds_sf300_orc.store_sales
, hive.tpcds_sf300_orc.customer
, hive.tpcds_sf300_orc.date_dim
WHERE ("ss_customer_sk" = "c_customer_sk")
AND ("ss_sold_date_sk" = "d_date_sk")
AND ("d_year" IN (2000      , (2000 + 1)      , (2000 + 2)      , (2000 + 3)))
GROUP BY "c_customer_sk"
)
)
, best_ss_customer AS (
SELECT
"c_customer_sk"
, "sum"(("ss_quantity" * "ss_sales_price")) "ssales"
FROM
hive.tpcds_sf300_orc.store_sales
, hive.tpcds_sf300_orc.customer
WHERE ("ss_customer_sk" = "c_customer_sk")
GROUP BY "c_customer_sk"
HAVING ("sum"(("ss_quantity" * "ss_sales_price")) > ((50 / DECIMAL '100.0') * (
SELECT *
FROM
max_store_sales
)))
)
SELECT "sum"("sales")
FROM
(
SELECT ("cs_quantity" * "cs_list_price") "sales"
FROM
hive.tpcds_sf300_orc.catalog_sales
, hive.tpcds_sf300_orc.date_dim
WHERE ("d_year" = 2000)
AND ("d_moy" = 2)
AND ("cs_sold_date_sk" = "d_date_sk")
AND ("cs_item_sk" IN (
SELECT "item_sk"
FROM
frequent_ss_items
))
AND ("cs_bill_customer_sk" IN (
SELECT "c_customer_sk"
FROM
best_ss_customer
))
UNION ALL    SELECT ("ws_quantity" * "ws_list_price") "sales"
FROM
hive.tpcds_sf300_orc.web_sales
, hive.tpcds_sf300_orc.date_dim
WHERE ("d_year" = 2000)
AND ("d_moy" = 2)
AND ("ws_sold_date_sk" = "d_date_sk")
AND ("ws_item_sk" IN (
SELECT "item_sk"
FROM
frequent_ss_items
))
AND ("ws_bill_customer_sk" IN (
SELECT "c_customer_sk"
FROM
best_ss_customer
))
)
LIMIT 100;
```

I still see stages with 6 nodes there. attached query json

[20200218_125448_00003_4enub.json.zip](https://github.com/prestosql/presto/files/4219285/20200218_125448_00003_4enub.json.zip)

**Comment by sopel39** [comment]
> Are you using any caching in between like Alluxio? It might be adding addresses to splits.

I don't use any caching.

**Comment by stagraqubole** [comment]
Able to repro it now, this is a different bug.

This is happening as this change https://github.com/prestosql/presto/commit/0debd99e41b0e8e5868347828d8df4c18297cedd announces all connectorIds from coordinator.

In SourceStageScheduler for probe side of broadcast join, we create tasks on all nodes that support the connector in case a cycle of scheduling had pending splits (in `finalizeTaskCreationIfNecessary`)

I am not sure why do we need to announce all connectors from coordinator when include-coordinator is false, c.c. @electrum 
If we keep this commit then we can change NodeSelector.allNodes to return only worker nodes when include-coordinator is false.
I dont see any user of this method calling it from expectation to get coordinator node necessarily, all are interested in nodes where they can schedule execution. So we can rename this method to something like getAllExecutionNodes for clarity.

**Comment by stagraqubole** [comment]
I have opened a PR with minimal changes as of now to fix this.
